import React, { useEffect } from 'react';

const PrivacyPolicy = () => {
  
  // Optional: Scroll to top on mount
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="privacy-policy-wrapper">
      {/* Banner Section */}
      <section className="inner_bnr">
        <div className="container">
          <div className="row">
            <div className="col-md-12">
              <div className="breadcrumb_area">
                <h1>Privacy Policy</h1>
                <ul>
                  <li><a href="/">Home</a></li>
                  <li> // </li>
                  <li>Privacy Policy</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Main Content Section */}
      <section className="inner_body">
        <div className="container">
          <div className="row">
            <div className="col-md-12">
              <p>
                This Privacy Policy describes Our policies and procedures on the collection, 
                use and disclosure of Your information when You respond to our advertisements 
                and tells You about Your privacy rights and how the law protects You. 
                We use Your Personal Data to contact and support you, as well as to provide 
                and improve the Service. By using the Service, You agree to the collection 
                and use of information in accordance with this Privacy Policy.
              </p>

              <h3>Interpretation</h3>
              <p>
                The words of which the initial letter is capitalized have meanings defined 
                under the following conditions. The following definitions shall have the 
                same meaning regardless of whether they appear in singular or in plural.
              </p>

              <h3>Definitions</h3>
              <p>For the purposes of this Privacy Policy:</p>
              <ul>
                <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Broadway.</li>
                <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                <li><strong>Service</strong> refers to the advertisement, website, or application.</li>
                <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
                <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                <li><strong>You</strong> means the individual accessing or using the Service.</li>
              </ul>

              <hr />

              <h3>Types of Data Collected</h3>
              <h4>Personal Data</h4>
              <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information including:</p>
              <ul>
                <li>First name and last name</li>
                <li>Email address</li>
                <li>Phone number</li>
                <li>Location details such as your address, city, or country</li>
                <li>Any other data such as personal preferences, requirements, or comments</li>
              </ul>

              <h3>Use of Your Personal Data</h3>
              <p>The Company may use Personal Data for the following purposes:</p>
              <ul>
                <li><strong>To provide and maintain our Service:</strong> monitoring usage and performance.</li>
                <li><strong>To manage Your Account:</strong> managing registration and providing access to functionalities.</li>
                <li><strong>For the performance of a contract:</strong> compliance and undertaking of purchase contracts.</li>
                <li><strong>To contact You:</strong> via email, calls, SMS, or push notifications for updates.</li>
                <li><strong>To provide You with news:</strong> special offers and general information about similar goods/services.</li>
                <li><strong>For business transfers:</strong> evaluating mergers or asset transfers.</li>
              </ul>

              <h3>Sharing Your Personal Information</h3>
              <p>We may share Your personal information in situations including:</p>
              <ul>
                <li><strong>With Service Providers:</strong> to monitor and analyze the use of our Service.</li>
                <li><strong>With Affiliates:</strong> requiring them to honor this Privacy Policy.</li>
                <li><strong>With Business Partners:</strong> to offer specific products or promotions.</li>
                <li><strong>With Your Consent:</strong> for any other purpose with your explicit permission.</li>
              </ul>

              <h3>Security of Your Personal Data</h3>
              <p>
                The security of Your Personal Data is important to Us, but remember that no method 
                of transmission over the Internet, or method of electronic storage is 100% secure. 
                While We strive to use commercially acceptable means to protect Your Personal Data, 
                We cannot guarantee its absolute security.
              </p>

              <div style={{ textAlign: 'center', marginTop: '40px' }}>
                <h3>Contact Us</h3>
                <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                <p><strong>Phone:</strong> <a href="tel:+919073338396">+91 9832064905</a></p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default PrivacyPolicy;